os: linux
dist: bionic 
language: minimal 
sudo: true 
install:
 - sudo apt install nginx
 - sudo unlink /etc/nginx/sites-enabled/default
 - ls /etc/nginx/sites-enabled
 - sudo systemctl reload nginx
 - sleep 5
script: curl localhost
